### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by baiRookie** [czl620/UFKit#1]
目前还差一个地址选择,我有一个plist文件,我想实现点击弹出自己的选择器怎么做,或者你的选择器怎么设置多列

**Comment by czl620** [comment]
1.0.1版本提供了地址选择，暂时只支持3列，并且在UFKit.bundle中提供了area.plist文件
.addRow([UFAreaPickerRow makeAreaPickerRow:^(UFAreaPickerRowMaker * _Nonnull make) {
                make
                .areaSeparator(@",")
                .title(@"地址")
                .name(@"address")
                .accessoryType(UFRowAccessoryDisclosureIndicator);

**Comment by baiRookie** [comment]
无法导入1.01版本

**Comment by baiRookie** [comment]
可能我仓库版本需要升级,正在解决

**Comment by czl620** [comment]
1.0.2版本支持自定义选择器

.addRow([UFCustomPickerViewRow makeCustomPickerViewRow:^(UFCustomPickerViewRowMaker * _Nonnull make) {
                make.
                delegate(weakSelf)
                .valueDidSelected(^(__kindof UFCustomPickerViewRow * _Nonnull row, UITextField * _Nonnull textField) {
                    NSString *value = @"你自定义选择的值";
                    row.value = value;
                    textField.text = value;
                })
                .title(@"自定义")
                .name(@"custom")
                .accessoryType(UFRowAccessoryDisclosureIndicator);
            }])

实现代理UFCustomPickerViewRowDelegate
- (NSInteger)numberOfComponentsInPickerViewRow:(nonnull UFCustomPickerViewRow *)pickerViewRow {
    return 5;
}

- (NSInteger)pickerViewRow:(nonnull UFCustomPickerViewRow *)pickerViewRow numberOfRowsInComponent:(NSInteger)component {
    return 10;
}

- (nonnull NSString *)pickerViewRow:(nonnull UFCustomPickerViewRow *)pickerViewRow titleForRow:(NSInteger)row forComponent:(NSInteger)component {
    return @"row";
}

- (void)pickerViewRow:(nonnull UFCustomPickerViewRow *)pickerViewRow didSelectRow:(NSInteger)row inComponent:(NSInteger)component {

}

**Comment by czl620** [comment]
仓库无导入的情况下 你可以添加UFKit.framework和UFKit.bundle到你的项目工程
添加Masonry、SDWebImage依赖即可
