### ISSUE TITLE
Xcode10 编译报错"___isPlatformVersionAtLeast", referenced from:

### ISSUE THREAD

**Issue by Monster9322** [czl620/UFKit#18]
"___isPlatformVersionAtLeast", referenced from:
      ___55-[UFUppercaseNumberBoard initWithFrame:inputViewStyle:]_block_invoke in UFKit(UFUppercaseNumberBoard.o)
      ___33-[UFProvinceBoard initWithFrame:]_block_invoke in UFKit(UFProvinceBoard.o)

**Comment by czl620** [comment]
iOS 8.0 or later
Xcode 11.0 or later
