### ISSUE TITLE
如何查询获取的城市的编码？

### ISSUE THREAD

**Issue by halfking** [czl620/UFKit#22]
UFKit写得很不错，非常好用。
我在使用地区时，发现没有地区编，在bundle中也没有看到地区编码之类的。能否使用国标编码，同时输出地区名字与编码，将这个控件再完善一下？
另，地区是否可以选择输出几级，如到市还是到区县一级？

谢谢你无私的风险。

**Comment by czl620** [comment]
你可以通过 UFCustomPickerViewRow来自定义你需要的应用场景
