### ISSUE TITLE
自定义地址无法联动

### ISSUE THREAD

**Issue by baiRookie** [czl620/UFKit#3]
就不能点击cell弹出自己选择器吗,目前这个自定义地址选择器的代理方法无法做到多列联动,即选中第一列时改变第二列数据

**Comment by czl620** [comment]
可以的，具体实现可以参照demo里的代码，有一个二级联动的例子

**Comment by czl620** [comment]
更新到1.0.3以上

**Comment by czl620** [comment]
点击某行的回调，你可以弹出你自己的pikerView，如果使用UFTextFieldRow需要设置editable为NO，你也可以直接使用UFRow
.rowDidSelected(^(__kindof UFRow * _Nonnull row) {
                    
                })

**Comment by baiRookie** [comment]
滑动第一列无法触发代理短点处不执行

发自我的 iPhone

**Comment by czl620** [comment]
> 滑动第一列无法触发代理短点处不执行 发自我的 iPhone
> […](#)
> 在 2019年8月1日，下午4:26，czl620 ***@***.***> 写道： 可以的，具体实现可以参照demo里的代码，有一个二级联动的例子 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

没明白你的意思，但是你还可以这样做：
使用点击某行的回调，弹出你自己的pikerView，如果使用UFTextFieldRow需要设置editable为NO失去输入焦点，你也可以直接使用UFRow
.rowDidSelected(^(__kindof UFRow * _Nonnull row) {

            })

**Comment by baiRookie** [comment]
行数代理，只在加载时调用一次，之后便不再调用，其他方法没问题


发自我的 iPhone

**Comment by baiRookie** [comment]
row选取的地址，怎么赋给textField


发自我的 iPhone

**Comment by baiRookie** [comment]
现在是拿到地址了，在row怎么把值显示出来


发自我的 iPhone

**Comment by baiRookie** [comment]
我一直用的swift，对oc一些东西不太敏感，这里这个值确实不知道如何显示在UFtextFieldRow上


发自我的 iPhone

**Comment by czl620** [comment]
row.value=你的值
[formview reloadData]
