### ISSUE TITLE
没有用pod，拖的

### ISSUE THREAD

**Issue by kthree0830** [czl620/UFKit#5]
[FZMineSettingViewController ufk_pickerImageForResult:]: unrecognized selector sent to instance 0x7fb1e274b0c0'

这个方法就崩溃

**Comment by czl620** [comment]
> [FZMineSettingViewController ufk_pickerImageForResult:]: unrecognized selector sent to instance 0x7fb1e274b0c0'
> 
> 这个方法就崩溃

Target->Buid Settings->Linking 下 Other Linker Flags 项添加-all_load
