### ISSUE TITLE
pods无法搜索到你的项目

### ISSUE THREAD

**Issue by carry1024** [czl620/UFKit#6]
pods无法搜索到你的项目，手动加载会有冲突

**Comment by czl620** [comment]
是可以搜索的到的
-> UFKit (1.1.6)
   A form framework for iOS.
   pod 'UFKit', '~> 1.1.6'
   - Homepage: https://github.com/czl620/UFKit
   - Source:   https://github.com/czl620/UFKit.git
   - Versions: 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.11, 1.0.10,
   1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0 [master
   repo]
手动添加有什么冲突呢？
