### ISSUE TITLE
密码输入框，可控制密码的显示与掩码

### ISSUE THREAD

**Issue by Ewenlong03** [czl620/UFKit#7]
希望可以加入密码的显示与掩码功能

**Comment by czl620** [comment]
是支持的 UFTextFieldRow及其子类均支持
make .secureTextEntry(YES)

**Comment by Ewenlong03** [comment]
> 是支持的 UFTextFieldRow及其子类均支持
> make .secureTextEntry(YES)
我添加了一个控制显示与掩码的按钮 点击后修改是否显示 修改了值 但是并没有生效

**Comment by czl620** [comment]
修改值后，需要执行formView的reloadData方法

**Comment by Ewenlong03** [comment]
> 是支持的 UFTextFieldRow及其子类均支持
> make .secureTextEntry(YES)

UFTextFieldRow *row = [self.formView findRowByName:@"newPwd"];
    row.secureTextEntry = !self.showPwdBtn.selected;

感谢您提供了如此使用的框架  请问能否开源呢

**Comment by Ewenlong03** [comment]
还有就是手机验证码的按钮目前还不支持表框属性设置吧

**Comment by czl620** [comment]
> 还有就是手机验证码的按钮目前还不支持表框属性设置吧

已经支持
